name: commit ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch submodules
        run: |
          git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Spotless code style check
        run: make spotless

      - name: Install dependency
        run: ./script/dependency.sh

      - name: Build Trime
        run: make debug

      - name: Upload Trime artifact
        uses: actions/upload-artifact@v2
        with:
          name: trime.zip
          path: app/build/outputs/apk/**/*v8a*.apk
          # keep 90 days
          retention-days: 90
